react-accordion-component - Jacob Husband
jacobhusband/c0822-code-solutions pull request #126
Opened 2022-10-26 23:38 UTC by jacobhusband

https://user-images.githubusercontent.com/24307282/198158597-4aa8cfdb-3d05-408c-8c83-3a61c59afd3e.mov

2022-10-26 23:43 UTC, thebearingedge requested changes

2022-10-26 23:43 UTC, thebearingedge commented on react-accordion-component/src/accordion.jsx
> +      children[i].lastElementChild.classList.add('hidden');
In React apps, we never do DOM manipulation like this. Everything is controlled by passing props to react elements.

2022-10-26 23:43 UTC, thebearingedge commented on react-accordion-component/src/accordion.jsx
> +      lastClicked: ''
Try simplifying this a bit. `lastClicked` can be an empty string, that's fine. When the user clicks a specific topic, set `lastClicked`. If they click the same thing again, set it back to an empty string.

2022-10-26 23:43 UTC, thebearingedge commented on react-accordion-component/src/accordion.jsx
> +  }
Instead of wrapping everything up in another component, just return the `<ul>` with the list items from your component above.

2022-10-26 23:43 UTC, thebearingedge commented on react-accordion-component/src/accordion.jsx
> +];
These should be passed to your component as a prop in `index.jsx`

2022-10-27 04:27 UTC, jacobhusband commented
https://user-images.githubusercontent.com/24307282/198191383-a960eac6-3680-49a9-9777-e3520e1d971d.mov

2022-10-27 14:36 UTC, thebearingedge approved these changes

2022-10-27 15:17 UTC, merged