javascript-carousel - Jacob Husband
jacobhusband/c0822-code-solutions pull request #72
Opened 2022-09-20 19:28 UTC by jacobhusband

https://user-images.githubusercontent.com/24307282/191347279-c0d3513e-d9c2-4fd4-826d-b7ba4749fd35.mov

2022-09-20 20:33 UTC, jacobhusband commented
https://user-images.githubusercontent.com/24307282/191358923-8100eeb3-1f58-4d5c-af8e-a2c173c75f7b.mov

2022-09-20 21:04 UTC, codingcodymiller requested changes

2022-09-20 21:04 UTC, codingcodymiller commented on javascript-carousel/main.js
> +}
Instead of doing this, I would keep a global variable that keeps track of the index of the current image.

2022-09-20 21:27 UTC, jacobhusband commented
https://user-images.githubusercontent.com/24307282/191367978-35b31b53-8a60-47e2-b726-fb44a21a1129.mov

2022-10-09 19:48 UTC, thebearingedge approved these changes

2022-10-10 18:43 UTC, merged