node-notes-cli - Jacob Husband
jacobhusband/c0822-code-solutions pull request #87
Opened 2022-10-12 23:36 UTC by jacobhusband

https://user-images.githubusercontent.com/24307282/195466975-e0a9576d-5c9f-40e2-a189-af417384076f.mov

2022-10-12 23:39 UTC, thebearingedge requested changes

2022-10-12 23:39 UTC, thebearingedge commented on node-notes-cli/delete.js
> +    data.nextId--;
We should not decrement the id. Once record 4 is deleted, it's deleted forever and nothing will take its place unless by updating it.

2022-10-12 23:43 UTC, jacobhusband commented
https://user-images.githubusercontent.com/24307282/195467593-56ce2531-3c90-425f-a84a-07a1ee8739ca.mov

2022-10-12 23:49 UTC, jacobhusband commented
![Screen Shot 2022-10-12 at 4 48 59 PM](https://user-images.githubusercontent.com/24307282/195468097-504b30d0-2a31-4a51-aa8e-16c5ba51cc61.png)

2022-10-13 16:16 UTC, thebearingedge requested changes

2022-10-13 16:16 UTC, thebearingedge commented on node-notes-cli/delete.js
> +    }
You can do this without a loop since you already know the user key.

```js
delete data.notes[userKey];
```

2022-10-13 16:16 UTC, thebearingedge commented on node-notes-cli/update.js
> +      }
You can do this without a loop too.

```js
if (userKey in data.notes) {
  // exists
} else {
  // doesn't exist
}
```

2022-10-13 16:20 UTC, jacobhusband commented
https://user-images.githubusercontent.com/24307282/195651546-70826d5d-77f6-4fe5-8cd1-ac1a365d25b7.mov

2022-10-13 16:43 UTC, jacobhusband commented
https://user-images.githubusercontent.com/24307282/195655867-4a79b955-3948-4a2c-b942-0bc4b514bfad.mov

Oof missed the other comment 😅

2022-10-13 16:55 UTC, thebearingedge approved these changes

2022-10-13 17:39 UTC, merged