express-notes-api - Jacob Husband
jacobhusband/c0822-code-solutions pull request #95
Opened 2022-10-15 22:06 UTC by jacobhusband

![Screen Shot 2022-10-15 at 3 05 02 PM](https://user-images.githubusercontent.com/24307282/196009348-60f0310d-cd31-4a8f-ac67-d70261502ab9.png)
![Screen Shot 2022-10-15 at 3 04 01 PM](https://user-images.githubusercontent.com/24307282/196009350-a4e446ee-f07a-4184-bac5-972f61c3c6c7.png)

2022-10-15 23:05 UTC, thebearingedge requested changes

2022-10-15 23:05 UTC, thebearingedge commented on express-notes-api/index.js
> +    }
You'll want to scan through all of your server code and include proper `else` or `return` statements to prevent the server from attempting to respond more than once to the same request.

2022-10-16 04:33 UTC, jacobhusband commented
![Screen Shot 2022-10-15 at 9 33 01 PM](https://user-images.githubusercontent.com/24307282/196018270-29c08289-2e63-49be-a24e-63dacfeb69cd.png)

2022-10-16 13:59 UTC, thebearingedge approved these changes

2022-10-16 15:19 UTC, merged